site_name: My knowledge Repo
theme:
  name: 'material'

nav: 
  - Home: 
    - 主页: index.md
    - 12月编程训练: 12月编程训练.md
    - 915真题: 915真题.md
    - 数二真题: 数二真题.md
  - 2023:
    - 23数学模拟卷: 23数学模拟卷.md
    - 23政治模拟卷: 23政治模拟卷.md

