site_name: My knowledge Repo
theme:
  name: 'material'

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
      
nav: 
  - Home: 
    - 主页: index.md
    - 12月编程训练: 12月编程训练.md
    - 915真题: 915真题.md
    - 数二真题: 数二真题.md
  - 2023:
    - 23数学模拟卷: 23数学模拟卷.md
    - 23政治模拟卷: 23政治模拟卷.md

