
site_name: My knowledge Repo
theme:
  name: 'material'

nav: 
  - Home: 
    - 主页: index.md
    - 12月编程训练: 12月编程训练.md
    - 24政治模拟卷: 24政治模拟卷.md
    - 渐进复杂度: 渐进复杂度.md
    - 915真题: 915真题.md
    - 数二真题: 数二真题.md
  - 2023:
    - 23数学模拟卷: 23数学模拟卷.md
    - 23政治模拟卷: 23政治模拟卷.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - neoteroi.cards
  - neoteroi.timeline
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search:
      separator: '[\s\u200b\-]'
      
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - css/custom.css 
    - css/neoteroi-mkdocs.css


